#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
SITE = ROOT / 'site'

def money(n):
    return '$' + format(n, ',.0f')

def main():
    SITE.mkdir(exist_ok=True)
    spend = json.loads((DATA / 'saas_spend.json').read_text())
    audit = json.loads((DATA / 'audit.json').read_text())
    ledger = json.loads((DATA / 'ledger.json').read_text())
    site_data = {
        'spend': spend,
        'audit': audit,
        'ledger': ledger,
        'format': {
            'before': money(audit['before_annual_spend']),
            'after': money(audit['after_annual_spend']),
            'savings': money(audit['annual_savings']),
            'success_fee': '$' + format(audit['success_fee_amount'], ',.0f'),
            'balance': '$' + format(ledger['balance_cents'] / 100, ',.2f'),
        },
    }
    (SITE / 'data.json').write_text(json.dumps(site_data, indent=2))
    (SITE / 'index.html').write_text(INDEX)
    (SITE / 'styles.css').write_text(STYLES)
    (SITE / 'app.js').write_text(APP)
    print(json.dumps({'ok': True, 'site': str(SITE / 'index.html'), 'data': str(SITE / 'data.json')}, indent=2))

INDEX = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otto Procurement Agent</title><link rel="stylesheet" href="styles.css"></head><body><header class="topbar"><div><p class="eyebrow">Hermes Agent Accelerated Business Hackathon</p><h1>Otto Procurement Agent</h1></div><div class="status-pill" id="paymentMode">loading</div></header><main><section class="hero card"><div><p class="eyebrow">Agent-run savings business</p><h2 id="headline">Loading audit...</h2><p id="thesis" class="lede"></p><div class="actions"><button>Approve savings audit</button><span>Run next SaaS scan</span></div></div><div class="metrics"><div><b id="before">--</b><span>Before spend</span></div><div><b id="savings">--</b><span>Found savings</span></div><div><b id="fee">--</b><span>Stripe success fee</span></div></div></section><section class="steps"><article><b>1 / SCOUT</b><h3>Ingest SaaS stack</h3><p>Seats, utilization, renewal timing, duplicate categories, and spend normalized into a procurement snapshot.</p></article><article><b>2 / SYNTHESIZE</b><h3>MoA council</h3><p>GPT-5.5 reference plus GLM 5.2 reference feed a GPT-5.5 aggregator that ranks savings by risk and effort.</p></article><article><b>3 / OPERATE</b><h3>Earn, spend, deliver</h3><p>Success-fee checkout event, operating-cost ledger, reinvestment, and buyer provisioning plan.</p></article></section><section class="card"><div class="section-head"><div><p class="eyebrow">Paid audit</p><h2>Before/after SaaS savings plan</h2></div><span id="generated"></span></div><div id="recommendations" class="recommendations"></div></section><section class="grid"><article class="card"><p class="eyebrow">Council transcript</p><h2>Visible MoA reasoning</h2><div id="council"></div></article><article class="card"><p class="eyebrow">Provisioning queue</p><h2>Agent-prepared operations</h2><div id="actions"></div></article></section><section class="grid"><article class="card"><p class="eyebrow">Treasury</p><h2>Revenue and spend ledger</h2><div id="ledger"></div></article><article class="card"><p class="eyebrow">Controls</p><h2>Safety limits</h2><div id="controls"></div><p class="small">Live customer-facing changes remain behind approval. The demo uses test-mode economics only.</p></article></section><section class="card proof"><p class="eyebrow">Submission proof</p><h2>Why this is a business, not a chatbot</h2><div><article><b>Earns</b><p>Success-fee checkout: 20% of annualized savings found by the agent.</p></article><article><b>Spends</b><p>MoA, ingestion, provisioning, and hosting costs debited under policy.</p></article><article><b>Runs ops</b><p>Prepares cancellation, migration, seat true-up, and buyer delivery payloads.</p></article></div></section></main><footer>Built with Hermes Agent + MoA for the Nous Research x NVIDIA x Stripe hackathon.</footer><script src="app.js"></script></body></html>'''

STYLES = r'''*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#ffffff;font-family:Inter,Arial,sans-serif;background-image:linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px);background-size:56px 56px}main,.topbar,footer{max-width:1180px;margin:auto}.topbar{display:flex;justify-content:space-between;align-items:center;padding:34px 20px 18px}.eyebrow{color:#ffd166;text-transform:uppercase;letter-spacing:.16em;font-size:13px;font-weight:900;margin:0 0 10px}h1{font-size:46px;letter-spacing:-.04em;margin:0;color:#fff}h2{font-size:34px;line-height:1.08;margin:0 0 14px;color:#fff}h3{margin:8px 0;color:#fff}.status-pill{border:1px solid #4ade80;color:#d1fae5;border-radius:99px;padding:9px 14px;background:#0f2a1a;font-weight:800}.card,.steps article{background:#111827;border:1px solid #40506c;border-radius:24px;box-shadow:0 20px 70px rgba(0,0,0,.35)}.hero{display:grid;grid-template-columns:1.7fr .8fr;gap:28px;padding:34px;margin:12px 20px}.lede{font-size:19px;line-height:1.58;color:#e5e7eb;max-width:800px}.actions{display:flex;gap:18px;align-items:center;margin-top:24px}button{background:#ffd166;border:0;border-radius:999px;padding:14px 20px;font-weight:900;color:#111}.actions span{color:#cbd5e1;font-weight:700}.metrics{display:grid;gap:16px}.metrics div{border:1px solid #50627f;border-radius:18px;padding:22px;background:#0f172a}.metrics b{display:block;color:#86efac;font-size:40px}.metrics span,.small{color:#e5e7eb}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:20px}.steps article{padding:22px}.steps b{color:#93c5fd}.steps p,.rec p,.proof p{color:#e5e7eb;line-height:1.45}.section-head{display:flex;justify-content:space-between;gap:16px;align-items:end}.section-head span{color:#f8fafc;font-size:14px;font-weight:700}.recommendations{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.rec{border:1px solid #50627f;border-radius:18px;padding:18px;background:#0f172a}.rec:nth-child(odd):last-child{grid-column:1/-1}.rec-top{display:flex;justify-content:space-between;gap:12px}.saving{color:#86efac;font-size:28px;font-weight:950;white-space:nowrap}.tags{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.tags span{background:#334155;border:1px solid #94a3b8;border-radius:99px;padding:6px 10px;color:#ffffff;font-size:13px;font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:20px}.grid .card,.proof.card{padding:24px}.line{display:grid;grid-template-columns:1fr auto;gap:16px;border-bottom:1px solid #334155;padding:12px 0}.pos{color:#86efac}.neg{color:#fca5a5}.proof{margin:20px}.proof>div{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.proof article{border:1px solid #50627f;border-radius:18px;padding:18px;background:#0f172a}a{color:#93c5fd}footer{padding:20px;color:#cbd5e1;text-align:center}@media(max-width:850px){.hero,.grid,.steps,.recommendations,.proof>div{grid-template-columns:1fr}h1{font-size:34px}}'''

APP = r'''function money(n){return '$'+Number(n).toLocaleString()}function cents(c){var s=c<0?'-':'';return s+'$'+(Math.abs(c)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}function title(k){var m={max_autonomous_ops_spend_cents:'Autonomous ops budget',live_spend_requires_human_approval:'Live spend approval',public_demo_dataset:'Demo dataset'};return m[k]||k.replaceAll('_',' ')}function val(k,v){if(k==='max_autonomous_ops_spend_cents')return '$'+(v/100).toLocaleString();if(typeof v==='boolean')return v?'Yes':'No';return v}function el(id){return document.getElementById(id)}function boot(){fetch('data.json').then(function(r){return r.json()}).then(function(data){var a=data.audit,l=data.ledger;el('paymentMode').textContent=(l.payment.mode==='local_stripe_style_test_event'?'Payment loop ready':l.payment.mode.replaceAll('_',' '));el('headline').textContent=a.headline;el('thesis').textContent=a.thesis;el('before').textContent=data.format.before;el('savings').textContent=data.format.savings;el('fee').textContent=data.format.success_fee;el('generated').textContent='Generated '+a.generated_at;el('recommendations').innerHTML=a.recommendations.map(function(r){return '<article class="rec"><div class="rec-top"><h3>'+r.action+'</h3><div class="saving">'+money(r.annual_savings)+'</div></div><p>'+r.why+'</p><div class="tags">'+r.vendors.map(function(v){return '<span>'+v+'</span>'}).join('')+'<span>effort: '+r.effort+'</span><span>risk: '+r.risk+'</span></div></article>'}).join('');el('council').innerHTML=a.council_transcript.map(function(c){return '<div class="line"><span><b>'+c.model+'</b><br><span class="small">'+c.position+'</span></span></div>'}).join('');el('actions').innerHTML=a.provisioning_actions.map(function(x){return '<div class="line"><span>'+x.step+'<br><span class="small">'+(x.approval_required?'Ready for human approval':'Ready for agent execution')+'</span></span><b>'+x.status+'</b></div>'}).join('');el('ledger').innerHTML=l.entries.map(function(e){return '<div class="line"><span>'+e.label+'<br><span class="small">'+e.timestamp+'</span></span><b class="'+(e.amount_cents>=0?'pos':'neg')+'">'+cents(e.amount_cents)+'</b></div>'}).join('')+'<div class="line"><span><b>Ending treasury</b></span><b class="pos">'+data.format.balance+'</b></div>';el('controls').innerHTML=Object.entries(l.safety_limits).map(function(kv){return '<div class="line"><span>'+title(kv[0])+'</span><b>'+val(kv[0],kv[1])+'</b></div>'}).join('')})}boot();'''

if __name__ == '__main__':
    main()
